PIL-975 Feature/contacts ens support
pillarwallet/pillarwallet pull request #2507
Opened 2021-03-04 13:49 UTC by mdjastrzebski

Scope:
- [x] Support for input of both hex address & ENS name for address field in Contact Dialog Modal
- [x] Streamline form validation using React Hook Form + yup 
- [x] Others changes
  - [x] Fix typos
  - [x] Improve behavior of `resolveName` from `utils/common`

2021-03-04 19:51 UTC, IAmKio commented on package.json
> +    "yup": "^0.32.9"
👍

2021-03-05 10:07 UTC, wjkg requested changes
I've found an edge case in the contact form that needs handling:

1. fill the name field
2. fill the address field with an ENS name that doesn't resolve
3. replace the address field with an ordinary (valid) address

result: error message is still shown and the save button doesn't work

Also, the button should probably be disabled when pressing it won't update the contact because the ENS name can't be found.

2021-03-05 13:50 UTC, mdjastrzebski commented on src/components/ContactSelector/ContactSelectorOptions.js
>    };
Good point! Fixed.

2021-03-05 13:50 UTC, mdjastrzebski commented
Re edge case handling: nice one! Fixed.

2021-03-05 13:53 UTC, mdjastrzebski commented
Re blocking save button: this is actually not so easy, because `errors` are populated only after validation has been triggered, which occurs only after first `onBlur` event (not from the start). So either we will duplicate validation code to handle button disabled OR we won't block it in the initial state. @wjkg wdyt?

2021-03-05 14:06 UTC, wjkg commented
The form library docs say there should be an `isDirty` flag in the form state. Could we use that to detect the initial state?

2021-03-05 14:33 UTC, mdjastrzebski commented
I've experimented with it, but it's still not 100% complete. E.g. after address `onBlur` event only address field will be validated, `formState.isDirty`, but name will be empty yet not validated.

Additionally from UX point of view, you might not know that name is a required field, and you might wonder why Save button is disabled. While if enable, you would get the validation message when pressing it.

IMO I would keep it as is, with active save button that can trigger helpful validation messages. @wjkg wdyt?

2021-03-05 15:11 UTC, wjkg approved these changes
I was thinking of consistency with e.g. new Sablier stream form, but after fixing that sticky error issue, validation on button press should be good enough. 

I've done some experimenting on my own, and `isValid` from form state _does_ take into account untouched required fields, but doesn't react to text changes without blur, so using it doesn't achieve validation while typing, anyway.

2021-03-10 09:28 UTC, merged