PIL-1130:- Change Max Ethereum Fee text
pillarwallet/pillarwallet pull request #2794
Opened 2021-07-30 08:02 UTC by divyaBacancy

![FeeLabel](https://user-images.githubusercontent.com/66996635/127621561-b3a32464-159a-478c-ad81-bb166c8820ac.png)

2021-07-30 15:23 UTC, IAmKio approved these changes

2021-07-30 15:58 UTC, poocart requested changes
Please also check string `allowancePlusEthFee` and there are more cases for `ethFee` (i.e. `DetailsTable` which is used in Exchange flow supported by Etherspot).

2021-08-02 06:02 UTC, divyaBacancy commented
@poocart Though etherspot is used, but it only uses ethereum chain here. 
Still do we need to handle?

2021-08-02 11:52 UTC, divyaBacancy commented
@poocart Done with the changes.

2021-08-02 13:23 UTC, poocart approved these changes

2021-08-02 13:32 UTC, merged