PIL-1140 Switch to in-app browser for WC Dashboard
pillarwallet/pillarwallet pull request #2809
Opened 2021-08-12 12:21 UTC by divyaBacancy

2021-08-12 12:52 UTC, IAmKio requested changes
Just a small thing for you to check Divya but aside from that, it looks good to me!

2021-08-12 12:52 UTC, IAmKio commented on src/screens/WalletConnect/Home/WalletConnectHome.js
> +  const enableURLInAppBrowser = firebaseRemoteConfig.getString(REMOTE_CONFIG.FEATURE_WC_DASHBOARD_INAPPBROWSER);
Is this supposed to be `.getBoolean` or something of that sort?

2021-08-12 15:39 UTC, IAmKio commented
@divyaBacancy so sorry, can we change the default value of the feature switch to false for now? Thank you

2021-08-13 04:32 UTC, divyaBacancy commented
@IAmKio Done.

2021-08-13 06:56 UTC, IAmKio approved these changes
LGTM

2021-08-13 07:26 UTC, merged