PIL-1242-Fiat formatting change
pillarwallet/pillarwallet pull request #2913
Opened 2021-11-15 09:17 UTC by vignesha22

![image](https://user-images.githubusercontent.com/82584664/141754671-21c2acec-1c22-4759-b0ef-6fcdb915736a.png)
just a sample image of how it will looks if the value is less than 0.01 but its not on code as from the pic above the token fiat value is 0 (it will display as zero).

2021-11-17 14:06 UTC, IAmKio requested changes
Just a minor change

2021-11-17 14:06 UTC, IAmKio commented on src/utils/format.js
> +  return BigNumber(formattedValue).lt(0.01) && BigNumber(formattedValue).gt(0) ? ('< ').concat(currencyValue) : currencyValue;
Split this into multiple lines please to make it cleaner, for example:

```suggestion
  return BigNumber(formattedValue)
    .lt(0.01) && BigNumber(formattedValue).gt(0) ? ('< ').concat(currencyValue) : currencyValue;
```

2021-11-18 10:09 UTC, divyaBacancy commented on src/utils/format.js
> +  // eslint-disable-next-line max-len
Remove this line as it is not required now

2021-11-18 10:09 UTC, divyaBacancy approved these changes
Just a minor change, otherwise LGTM

2021-11-18 22:35 UTC, IAmKio approved these changes

2021-11-18 23:10 UTC, merged