PIL-1211-Wallet Backup & Import Settings
pillarwallet/pillarwallet pull request #2914
Opened 2021-11-15 13:30 UTC by divyaBacancy

2021-11-17 21:11 UTC, IAmKio requested changes
Just a few minor things - thank you!

2021-11-17 21:11 UTC, IAmKio commented on src/screens/RevealBackupPhrase/RevealBackupPhrase.js
> +    }
Maybe?

```suggestion
      Toast.show({ message: isPrivateKey ? t('toast.privateKeyCopiedToClipboard') :  t('toast.seedPhraseCopiedToClipboard'), emoji: 'ok_hand', autoClose: true });
```

2021-11-17 21:11 UTC, IAmKio commented on src/utils/themes.js
> +  toastBackgroundColor: '#2e673c',
Could we add this to the theme please?

2021-11-18 07:28 UTC, divyaBacancy commented on src/screens/RevealBackupPhrase/RevealBackupPhrase.js
> +    }
Done

2021-11-18 07:28 UTC, divyaBacancy commented on src/utils/themes.js
> +  toastBackgroundColor: '#2e673c',
Done

2021-11-23 10:35 UTC, IAmKio approved these changes
Great work! 🙏

2021-11-23 13:40 UTC, merged