PIL-1210-Terms of Service UI
pillarwallet/pillarwallet pull request #2916
Opened 2021-11-17 11:38 UTC by divyaBacancy

https://user-images.githubusercontent.com/66996635/142193773-bb8f0e97-bdac-4389-8214-c9bc7c7402b9.mov

https://user-images.githubusercontent.com/66996635/142193780-cf68d29b-114c-4337-84ae-51178fb88657.mov

2021-11-17 21:00 UTC, IAmKio requested changes
Just a few minor things in regards to our earlier discussion on splitting out the screens - cheers!

2021-11-25 11:06 UTC, divyaBacancy commented
Done with the PR comments. 

https://user-images.githubusercontent.com/66996635/143430269-7bd90778-773e-4b27-aecb-f597b8cf9574.mov

2021-11-25 11:06 UTC, IAmKio requested changes
3 comments but they're all the name, just the renaming of a const for consistency. Thanks!

2021-11-25 11:06 UTC, IAmKio commented on src/screens/NewProfile/NewProfile.js
> +import { PERMISSIONS, SET_WALLET_PIN_CODE, TERMS_AND_PRIVACY } from 'constants/navigationConstants';
Could we change this to `LEGAL_MODAL` or something similar for consistency with the rest of the naming please?

2021-11-25 11:06 UTC, IAmKio commented on src/screens/Menu/Menu/components/MenuFooter.js
> +  TERMS_AND_PRIVACY,
Could we change this to LEGAL_MODAL or something similar for consistency with the rest of the naming please?

2021-11-25 11:06 UTC, IAmKio commented on src/navigation/appNavigation.js
> +    [TERMS_AND_PRIVACY]: TermsAndPrivacyScreen,
Could we change this to LEGAL_MODAL or something similar for consistency with the rest of the naming please?

2021-11-25 11:51 UTC, IAmKio approved these changes

2021-11-25 11:57 UTC, merged