PIL-1212-Enable Touch ID Modal and  PIL-1209-Alter App Startup
pillarwallet/pillarwallet pull request #2927
Opened 2021-11-22 12:51 UTC by divyaBacancy

https://user-images.githubusercontent.com/66996635/142864852-e32a1e02-4212-410d-8d7b-c93f8bb99763.mov

2021-12-02 07:51 UTC, divyaBacancy commented
https://user-images.githubusercontent.com/66996635/144380147-584d31e2-70bc-4c78-99af-01e5b24c21ad.mov

2021-12-28 06:36 UTC, divyaBacancy commented
https://user-images.githubusercontent.com/66996635/147535705-9cbaae56-068b-4581-bf1e-6f8b02ff0c78.mov

2021-12-30 15:23 UTC, Yash-Chaubal approved these changes
LGTM!

2022-01-06 01:49 UTC, IAmKio requested changes
Just a few minor points but it's looking great!

2022-01-06 01:49 UTC, IAmKio commented on src/actions/onboardingActions.js
> +    await dispatch(setupAppServicesAction(privateKey));
Do you know if we actually need to `await` these `dispatch`es?

2022-01-06 01:49 UTC, IAmKio commented on src/components/Modal/Modal.js
> +  noCloseOnBackdropPress?: boolean,
I think something like `backdropDismissable` is more readable?

2022-01-06 01:49 UTC, IAmKio commented on src/components/SwipeButton/SwipeButton.js
> +};
Thanks for making this a component 🙏

2022-01-06 01:49 UTC, IAmKio commented on src/components/SwipeButton/SwipeButton.js
> +import { fontSizes, spacing, appFont } from 'utils/variables';
```suggestion
// Components
import Icon from 'components/core/Icon';

// Utils
import { fontSizes, spacing, appFont } from 'utils/variables';
```

2022-01-12 11:50 UTC, closed without merging