PRO-161 Task: Android Dependencies Update
pillarwallet/pillarwallet pull request #3049
Opened 2022-05-18 09:39 UTC by divyaBacancy

jcenter to maven central migration and update some dependencies.

2022-05-18 10:18 UTC, divyaBacancy commented
> 🤞 fingers crossed!

Good Luck!

2022-05-19 12:29 UTC, IAmKio requested changes
Just one small thing - other than that, LGTM

2022-05-19 12:43 UTC, divyaBacancy commented on android/app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="true"
allowBackup false means application data can not be backed up and restored by the user using adb backup and adb restore. As per Ardian suggestion we had set android:allowBackup false.

2022-05-19 12:59 UTC, divyaBacancy commented on android/app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="true"
android:fullBackupContent attribute points to an XML file that contains full backup rules for [Auto Backup](https://developer.android.com/guide/topics/data/autobackup). These rules determine what files get backed up.

android:fullBackupContent is mandatory for com.instabug.library:instabug-core:10.13.0
For more details: https://developer.android.com/guide/topics/manifest/application-element

2022-05-19 13:01 UTC, IAmKio approved these changes
LGTM

2022-05-19 13:15 UTC, merged