PRO-336 Add Optimism Network
pillarwallet/pillarwallet pull request #3085
Opened 2022-07-25 13:44 UTC by hemadri-tank-bacancy

Add new optimism network

https://user-images.githubusercontent.com/78720269/180791594-135dc047-be84-4237-9828-c32acf90519d.mp4

2022-07-25 20:18 UTC, IAmKio requested changes
Just a few minor things but other than that - LGTM!

2022-07-25 20:18 UTC, IAmKio commented on src/utils/uiConfig.js
> +        chartColor: string,
And the same as above, this might just be a pattern i've never seen before...

2022-07-26 06:56 UTC, hemadri-tank-bacancy commented on src/utils/chains.js
> +  [CHAIN_ID.OPTIMISM_KOVAN]: CHAIN.OPTIMISM,
@IAmKio Do you mean OPTIMISM_KOVAN string replace with other string?

2022-07-26 06:56 UTC, hemadri-tank-bacancy commented on src/services/etherspot.js
> +    console.log('');
Resolved!

2022-07-26 08:53 UTC, IAmKio commented on src/utils/chains.js
> +  [CHAIN_ID.OPTIMISM_KOVAN]: CHAIN.OPTIMISM,
@hemadri-tank-bacancy sorry, i'm referring to the `CHAIN.OPTOMISM` constant. If i understand this correctly, this means that in the UI the name will resolve to "Optimism"? If it does, could we please change this to "Optimism Kovan" for clarity when running in testnet mode?

2022-07-26 10:12 UTC, hemadri-tank-bacancy commented on src/utils/chains.js
> +  [CHAIN_ID.OPTIMISM_KOVAN]: CHAIN.OPTIMISM,
"Optimism Kovan" name visible in staging

2022-07-27 08:33 UTC, IAmKio approved these changes
LGTM - thank you!

2022-07-27 08:33 UTC, IAmKio commented on src/utils/chains.js
> +  [CHAIN_ID.OPTIMISM_KOVAN]: CHAIN.OPTIMISM,
Perfect thank you

2022-07-27 08:45 UTC, merged