PRO-425 Gas Fee Payment Asset Selection
pillarwallet/pillarwallet pull request #3127
Opened 2022-09-16 14:15 UTC by hemadri-tank-bacancy

* Select Gas fee asset

https://user-images.githubusercontent.com/78720269/190658768-0d6c21cc-b5a4-4c47-9058-13797ccd930e.mp4

2022-09-16 14:27 UTC, IAmKio requested changes
Just a few minor points but other than that - great work!

2022-09-16 14:27 UTC, IAmKio commented on src/screens/Bridge/Exchange-CrossChain/GasFeeAssetSelection.tsx
> +        onPress={async () => {
Do we need async here?

2022-09-16 14:27 UTC, IAmKio commented on src/screens/Bridge/Exchange-CrossChain/GasFeeAssetSelection.tsx
> +                ? item.balance.balance?.toFixed(1) + ' ' + symbol + '  •  ' + item?.formattedBalanceInFiat
Consider using template literals in future

2022-09-21 08:47 UTC, hemadri-tank-bacancy commented on src/screens/Bridge/Exchange-CrossChain/GasFeeAssetSelection.tsx
> +        onPress={async () => {
Resolved it!

2022-09-21 08:47 UTC, hemadri-tank-bacancy commented on src/screens/Bridge/Exchange-CrossChain/GasFeeAssetSelection.tsx
> +                ? item.balance.balance?.toFixed(1) + ' ' + symbol + '  •  ' + item?.formattedBalanceInFiat
Resolved it!

2022-09-21 12:19 UTC, IAmKio approved these changes
LGTM and thank you

2022-09-21 12:20 UTC, merged