PRO-1448 Initial Set up Animation
pillarwallet/pillarwallet pull request #3319
Opened 2023-06-16 13:50 UTC by lalitkumarrock

https://linear.app/pillarproject/issue/PRO-1448/pillar-wallet-initial-set-up-animation

## Description

- Introduced animation loader with processing status in initial setup.

## How Has This Been Tested?

- Tested on Android Device
- Tested on Simulator 14 pro

## Screenshots (if appropriate):
For new user:
https://github.com/pillarwallet/pillarwallet/assets/82652040/82b059af-09ad-4aaa-82a6-d294a801a811

For existing user:
https://github.com/pillarwallet/pillarwallet/assets/82652040/d0572621-5454-4483-8f4f-8c2324473be8

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-06-28 13:00 UTC, IAmKio requested changes
Just a few small comments but other than that - looking good

2023-06-29 06:55 UTC, lalitkumarrock commented on src/components/SkeletonLoader/OnboardingLoaders.tsx
> +        height={JSON.stringify(height)}
Yes, radius, width and height is hardcoded. here made just common component.

2023-06-29 07:30 UTC, lalitkumarrock commented on src/actions/onboardingActions.js
> +    }
It's stuck on particular event.

https://github.com/pillarwallet/pillarwallet/assets/82652040/1b01fa5a-c419-462b-85e3-dd46619cb964

2023-06-29 07:38 UTC, lalitkumarrock commented on src/actions/onboardingActions.js
> +    }, 0);
Yes, you are right. But somehow it takes 3 to 4 seconds to dismiss the Ready! text. It takes longer due to many background processes.

2023-06-30 00:33 UTC, IAmKio commented on src/actions/onboardingActions.js
> +    }, 0);
Ahh okay, understood!

2023-06-30 00:34 UTC, IAmKio commented on src/actions/onboardingActions.js
> +    }
We should probably handle this a bit better... can we retry the process with a backoff?

2023-06-30 00:34 UTC, IAmKio commented on src/components/SkeletonLoader/OnboardingLoaders.tsx
> +        height={JSON.stringify(height)}
Got it, thanks!

2023-06-30 07:14 UTC, lalitkumarrock commented on src/actions/onboardingActions.js
> +    }
Here calls multiple dispatch at a time. So difficult to manage the backoff retry process individually.

2023-07-05 07:14 UTC, IAmKio commented on src/actions/onboardingActions.js
> +    }
Just picking this up again @lalitkumarrock  - we're going to need to deal with this as we can't have users bring stuck here in any way as first impressions count. This breaking in any way due to network issues or server errors will need to either retry or restart the process. I'll leave it up to you to decide the best course of action but users can't get stuck here for sure.

2023-07-05 13:22 UTC, lalitkumarrock commented on src/actions/onboardingActions.js
> +    }
Okay, I'll find out the best solution

2023-07-14 05:04 UTC, lalitkumarrock commented on src/actions/onboardingActions.js
> +    }
@IAmKio Please review it. https://github.com/pillarwallet/pillarwallet/pull/3319/commits/e86a7f44377aae67d9216599de916c2b7f0a9387

https://github.com/pillarwallet/pillarwallet/assets/82652040/621f526c-b4cb-4b57-856c-9ed000fb35af

2023-07-14 13:54 UTC, IAmKio commented on src/actions/onboardingActions.js
> +    }
Great work @lalitkumarrock - as we just discussed, if you could change the "No internet" to "No internet, retrying..." to indicate to the user that we're handling it. Thank you

2023-07-14 14:20 UTC, lalitkumarrock commented on src/actions/onboardingActions.js
> +    }
Text updated.

2023-07-14 14:28 UTC, merged