PRO-1542 Fix Pool Activity and Trending History Screen
pillarwallet/pillarwallet pull request #3322
Opened 2023-06-21 15:27 UTC by lalitkumarrock

https://linear.app/pillarproject/issue/PRO-1542/pillar-wallet-fix-pool-activity-and-trending-history-screen

## Description

- Fixed Trending History and Pool Activity screen data.

## How Has This Been Tested?

- Tested on Simulator 14 PRO
- Tested on Android Device

## Screenshots (if appropriate):
https://github.com/pillarwallet/pillarwallet/assets/82652040/27f496d1-b317-4d13-a61e-5932a47e7e90

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-06-21 16:37 UTC, MayukhSamadder2000 commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +interface Props {
```suggestion
interface TokenAnalyticsActivityListProps {
```

2023-06-21 16:38 UTC, MayukhSamadder2000 commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +const TokenAnalyticsActivityList = ({ data, isTreding }: Props) => {
```suggestion
const TokenAnalyticsActivityList = ({ data, isTreding }: TokenAnalyticsActivityListProps) => {
```

2023-06-21 16:38 UTC, MayukhSamadder2000 commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +const TokenAnalyticsActivityList = ({ data, isTreding }: Props) => {
`isTreding` should be is `isTrading` right?

2023-06-21 18:08 UTC, MayukhSamadder2000 requested changes
LOC

2023-06-22 07:02 UTC, lalitkumarrock commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +  const tokenB = isTreding ? tokensOut[0] : !isEmpty(tokensIn) ? tokensIn[1] : tokensOut[1];
I updated it

2023-06-22 07:03 UTC, lalitkumarrock commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +function getDateDiff(startDate, endDate) {
It has been moved to the common utils file.

2023-06-22 07:03 UTC, lalitkumarrock commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +interface Props {
Updated it.

2023-06-22 07:04 UTC, lalitkumarrock commented on src/screens/Asset/components/TokenAnalyticsActivityList.tsx
> +const TokenAnalyticsActivityList = ({ data, isTreding }: Props) => {
Yes, should be. I updated it

2023-06-22 10:52 UTC, MayukhSamadder2000 approved these changes
LGTM

2023-06-22 10:53 UTC, merged