PRO-2031 Archanova Error
pillarwallet/pillarwallet pull request #3466
Opened 2023-11-30 05:54 UTC by lalitkumarrock

https://linear.app/pillarproject/issue/PRO-2039/story-task-archanova-error

## Description

- Fixed: Multiple times Archanova init
- Fixed: Archanova disconnect error

## Motivation and Context

## How Has This Been Tested?

- Tested on Android device

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-12-04 16:14 UTC, IAmKio requested changes
Am i right in thinking that the only thing that is changed here is just the private key initialisation?

2023-12-04 16:14 UTC, IAmKio commented on src/services/archanova.js
> +    this.privateKey === '';
Is this supposed to be `=== ''`?

2023-12-05 05:33 UTC, lalitkumarrock commented on src/services/archanova.js
> +    this.privateKey === '';
My bad, I'll fix it ASAP.

2023-12-05 05:37 UTC, lalitkumarrock commented
> Am i right in thinking that the only thing that is changed here is just the private key initialisation?

This issue occurs when we have already initialized the sdk and try to restart again.
The private key compares the previous key and the next key for initialization.

2023-12-05 10:45 UTC, IAmKio approved these changes
LGTM

2023-12-05 11:37 UTC, merged